services:
  backend:
    build:
      context: ./SocialiX-Backend
    container_name: socialix-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./SocialiX-Frontend
    container_name: socialix-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: socialix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThoughtWireSQL
      POSTGRES_DB: socialix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d socialix"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: